version: '3.5'

services:
#  tika:
#    image: 'apache/tika:1.24'
#    restart: always
#    ports:
#      - '9998:9998'
#
#  elasticsearch:
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.0' 
#    restart: always
#    ports:
#      - '9200:9200'
#      - '9300:9300'
#    environment: 
#      - 'discovery.type=single-node'
#
#  postgres:
#    image: postgres
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    networks:
#      - postgres
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
# 
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      - postgres
#    restart: unless-stopped
#
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.210.166:8071'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8071:8071'
      - '4471:443'
      - '8022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
  

#  portainer:
#    image: portainer/portainer
#    command: -H unix:///var/run/docker.sock
#    restart: always
#    ports:
#      - 9000:9000
#      - 8000:8000
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#
#networks:
#  postgres:
#    driver: bridge
#
#volumes:
#  portainer_data:
#  postgres:
#  pgadmin:
